# Generated by Django 3.1 on 2021-03-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Psid', models.IntegerField()),
                ('First_name', models.CharField(max_length=70)),
                ('Last_name', models.CharField(max_length=70)),
                ('Skill', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Psid', models.IntegerField()),
                ('First_name', models.CharField(max_length=70)),
                ('Last_name', models.CharField(max_length=70)),
            ],
        ),
    ]
